import {Component,OnInit,OnDestroy,EventEmitter,Output} from '@angular/core';
import template from './categories.component.html';
import style from './categories.component.scss';
@Component({
  selector:'categories',
  template,
  styles:[style]
})
export class CategoriesComponent implements OnInit,OnDestroy{
  height:number=0;
  categoriesPage:boolean=true;
  ELECTRONICSpage:boolean=false;
  NETWORKpage:boolean=false;
  AVpage:boolean=false;
  TVpage:boolean=false;
  SOUNDpage:boolean=false;
  ENTERTAINMENTpage:boolean=false;
  SECURITYpage:boolean=false;
  SECURITY_SYSTEMpage:boolean=false;
  THERMOSTATpage:boolean=false;
  SMOKEpage:boolean=false;
  INSTRUCTIONpage:boolean=false;
  APPLEpage:boolean=false;
  MICROSOFTpage:boolean=false;
  EXCELpage:boolean=false;
  GOOGLEpage:boolean=false;
  SMARTPHONEpage:boolean=false;
  WINDOWSpage:boolean=false;
  MACpage:boolean=false;
  COMPUTERpage:boolean=false;
  BACKUPpage:boolean=false;
  MIGRATEpage:boolean=false;
  VIRUSpage:boolean=false;
  SERVICEpage:boolean=false;
  PRINTERpage:boolean=false;
  WIRELESSpage:boolean=false;
  OTHER_WORKSpage:boolean=false;
  OTHERpage:boolean=false;
  hideENTERTAINMENT4:boolean=true;
  hideENTERTAINMENT3:boolean=true;
  hideENTERTAINMENT2:boolean=true;
  hideENTERTAINMENT1:boolean=true;
  hideSOUND4:boolean=true;
  hideSOUND3:boolean=true;
  hideSOUND2:boolean=true;
  hideSOUND1:boolean=true;
  hideSCREEN4:boolean=true;
  hideSCREEN3:boolean=true;
  hideSCREEN2:boolean=true;
  hideSCREEN1:boolean=true;
  hideSECURITY4:boolean=true;
  hideSECURITY3:boolean=true;
  hideSECURITY2:boolean=true;
  hideSECURITY1:boolean=true;
  hideTHERMOSTAT4:boolean=true;
  hideTHERMOSTAT3:boolean=true;
  hideTHERMOSTAT2:boolean=true;
  hideTHERMOSTAT1:boolean=true;
  hideSMOKE4:boolean=true;
  hideSMOKE3:boolean=true;
  hideSMOKE2:boolean=true;
  hideSMOKE1:boolean=true;
  hideAPPLE4:boolean=true;
  hideAPPLE3:boolean=true;
  hideAPPLE2:boolean=true;
  hideAPPLE1:boolean=true;
  hideMICROSOFT4:boolean=true;
  hideMICROSOFT3:boolean=true;
  hideMICROSOFT2:boolean=true;
  hideMICROSOFT1:boolean=true;
  hideEXCEL4:boolean=true;
  hideEXCEL3:boolean=true;
  hideEXCEL2:boolean=true;
  hideEXCEL1:boolean=true;
  hideGOOGLE4:boolean=true;
  hideGOOGLE3:boolean=true;
  hideGOOGLE2:boolean=true;
  hideGOOGLE1:boolean=true;
  hideSMARTPHONE4:boolean=true;
  hideSMARTPHONE3:boolean=true;
  hideSMARTPHONE2:boolean=true;
  hideSMARTPHONE1:boolean=true;
  hideWINDOWS4:boolean=true;
  hideWINDOWS3:boolean=true;
  hideWINDOWS2:boolean=true;
  hideWINDOWS1:boolean=true;
  hideMAC4:boolean=true;
  hideMAC3:boolean=true;
  hideMAC2:boolean=true;
  hideMAC1:boolean=true;
  hideBACKUP4:boolean=true;
  hideBACKUP3:boolean=true;
  hideBACKUP2:boolean=true;
  hideBACKUP1:boolean=true;
  hideMIGRATE4:boolean=true;
  hideMIGRATE3:boolean=true;
  hideMIGRATE2:boolean=true;
  hideMIGRATE1:boolean=true;
  hideVIRUS4:boolean=true;
  hideVIRUS3:boolean=true;
  hideVIRUS2:boolean=true;
  hideVIRUS1:boolean=true;
  hideSERVICE4:boolean=true;
  hideSERVICE3:boolean=true;
  hideSERVICE2:boolean=true;
  hideSERVICE1:boolean=true;
  hidePRINTER4:boolean=true;
  hidePRINTER3:boolean=true;
  hidePRINTER2:boolean=true;
  hidePRINTER1:boolean=true;
  hideWIRELESS4:boolean=true;
  hideWIRELESS3:boolean=true;
  hideWIRELESS2:boolean=true;
  hideWIRELESS1:boolean=true;
  hideOTHER4:boolean=true;
  hideOTHER3:boolean=true;
  hideOTHER2:boolean=true;
  hideOTHER1:boolean=true;
  addressPage:boolean=false;
  @Output() onBack:EventEmitter<any>=new EventEmitter();
  @Output() onSubmit:EventEmitter<any>=new EventEmitter();
  constructor(){}
  ngOnInit(){
    this.height=window.innerHeight-125;
  }
  back(){
    this.onBack.emit(null);
  }
  submit(){
    this.onSubmit.emit(null);
  }
  ngOnDestroy(){
  }
}